name: PS Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 매일 자정 갱신
  workflow_dispatch: # 수동 실행 가능
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.calendar.full.svg
          base: "" # 기본 프로필 통계 숨김
          plugin_calendar: yes
          plugin_calendar_limit: 1 # 1년치
          repositories: PS